$schema: "https://json-schema.org/draft/2020-12/schema"
description: entries for the sample sheet
properties:
  sample:
    type: string
    description: sample name/identifier
  read1:
    type: string
    description: path to FASTQ file (R1 for paired-end, or the single-end file)
  read2:
    type: string
    description: path to FASTQ file (R2, paired-end only; leave blank for single-end)

required:
  - sample
  - read1
